### ISSUE TITLE
Add support for sendMessageReturnHash

### ISSUE THREAD

**Issue by akme** [xssnick/tonutils-go#123]
It would be great to have [raw.sendMessageReturnHash](https://github.com/ton-blockchain/ton/blob/master/tl/generate/scheme/tonlib_api.tl#LL265C59-L265C59) implemented in addition to raw.sendMessage.
My idea is that it would bring more info for tx flow, like getting something similar to txid on send, so we can generate a link for different explorers.

**Comment by xssnick** [comment]
Hi, wallet already has method `SendManyGetInMsgHash`, it will return message hash immediately after sending. Wallet also has `FindTransactionByInMsgHash` method, with allows you to wait confirmation by msg hash.

If you want to get message hash for manual external message sending you could do like that:
```golang
msg := &tlb.ExternalMessage{
    DstAddr: addr,
    Body:    data,
}
hash := msg.Body.Hash()

api.SendExternalMessage(ctx, msg)
```

**Comment by akme** [comment]
Oh, that's interesting, thank you for clarification, will try your approach.

**Comment by xssnick** [comment]
Hey, have you tried to use 128 + 32 send mode with 0 in amount? I think msg hash should match for that

**Comment by akme** [comment]
We are doing exactly this, but no hashes are matching, is there any chance that for V3R1 hashes should be calculated differently?

**Comment by xssnick** [comment]
No, hashed for v3r1 should be same, i will check this case later

**Comment by xssnick** [comment]
I researched this case and did some tests. The problem is actually not with message hash, but with account destruction (32 msg mode). When account is destroyed - liteserver drops account's transaction history, so we cannot find transaction. LS is doing it because after next activation, transaction chain cannot be proven using list transactions, each transaction should have reference on previous one, but destroying is breaking this chain.

So the solution is simple, just use 128 without + 32, then account keeps active without balance for some time and will be frozen automatically later.
