### ISSUE TITLE
findLastTransactionByHash does not work as expected

### ISSUE THREAD

**Issue by troo** [xssnick/tonutils-go#217]
1. Only first transaction in txList for out message checked:

```go
		for i, transaction := range txList {
			if i == 0 {
				// get previous of the oldest tx, in case if we need to scan deeper
				lastLt, lastHash = txList[0].PrevTxLT, txList[0].PrevTxHash
			}

			if isOut {
				if transaction.IO.Out == nil {
					continue
				}

				list, err := transaction.IO.Out.ToSlice()
				if err != nil {
					return nil, fmt.Errorf("cannot list out messages: %w", err)
				}

				for _, m := range list {
					if bytes.Equal(m.Msg.Payload().Hash(), msgHash) {
						return transaction, nil
					}
				}
                  // TODO: continue required for other transactions check 
                 // TODO: return transaction, nil at the end of range txList { also should be fixed
...
```

2. m.Msg.Payload().Hash() calculation seems wrong. It calculates hash different than what is displayed in ton explorer. Transaction hash remains correct.

**Comment by Arezu1360** [comment]
Yes

**Comment by xssnick** [comment]
1. As i see in master branch, [it checks all transactions until limit](https://github.com/xssnick/tonutils-go/blob/master/ton/transactions.go#L307), not just one.

2. This is the hash of payload, it is used for data comparing, explorers probably shows full external message hash, but it changes after commit and could not be used to find transaction since it is not known on moment of external push.

**Comment by xssnick** [comment]
[Fixed in dev branch](https://github.com/xssnick/tonutils-go/commit/5bacf22c3461fc1b266285c4116ea3f5cd50d1ff)
