### ISSUE TITLE
How to use `tlb` struct tag to load string snake?

### ISSUE THREAD

**Issue by mritd** [xssnick/tonutils-go#220]
I've looked at the docs in the [loader.go](https://github.com/xssnick/tonutils-go/blob/master/tlb/loader.go#L46), but still haven't figured out how to load the string snake; for now I'm stuck with the `*cell.Cell`:

```golang
var comment struct {
    _     tlb.Magic  `tlb:"#00000000"`
    Value *cell.Cell `tlb:"."`
}
_ = tlb.LoadFromCell(&comment, msgs[1].AsInternal().Body.BeginParse(), false)

// load string snake
cStr, err := comment.Value.BeginParse().LoadStringSnake()
```

I'm wondering if there are other ways to directly deserialize structs, such as `tlb: "snake"`?

**Comment by xssnick** [comment]
Hi, at this moment no, snake has no special tag, because it is pretty rare. 

For your case it will be better to implement custom `LoadFromCell` method for `comment` type, and it will be called automatically instead of parsing tags.

Example https://github.com/xssnick/tonutils-go/blob/master/tlb/account.go#L128-L163
